language: php
php:
  - '7.3'

dist: xenial

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

services:
  - postgresql
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - psql -c 'create database hireinsocial_test;' -U postgres
  - psql -c "CREATE USER hireinsocial WITH PASSWORD 'hireinsocial';" -U postgres

install:
  - cd php/hireinsocial
  - composer install

script:
  - composer run test
  - phpdbg -qrr ./vendor/bin/infection -vvv --test-framework-options='--testsuite=unit' --only-covered