language: php
php:
  - '7.2'
dist: xenial

services:
  - postgresql
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - sudo chown -R travis:travis $TRAVIS_BUILD_DIR/
  - psql -c 'create database hireinsocial_test;' -U postgres
  - psql -c "CREATE USER hireinsocial WITH PASSWORD 'hireinsocial';" -U postgres

install:
  - cd php/hireinsocial
  - composer install

script:
  - composer run test
  - phpdbg -qrr ./vendor/bin/infection -vvv --test-framework-options='--testsuite=unit' --only-covered