language: php
php:
  - '7.3'

dist: xenial

addons:
  postgresql: "11.2"

services:
  - postgresql
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

install:
  - cd php/hireinsocial
  - composer install --no-interaction --optimize-autoloader

before_script:
  - psql --version
  - psql -c 'create database hireinsocial_test;' -U postgres
  - psql -c "CREATE USER hireinsocial WITH PASSWORD 'hireinsocial';" -U postgres

script:
  - composer run test
  - phpdbg -qrr ./vendor/bin/infection -vvv --test-framework-options='--testsuite=unit' --only-covered