language: php
php:
  - '7.2'
dist: xenial

services:
  - postgresql
  - redis-server

before_install:
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - cd php/hireinsocial
  - composer install

script:
  - composer run test