<?php

declare (strict_types=1);

namespace HireInSocial\Tests\Application\Functional;

use HireInSocial\Application\System;
use HireInSocial\Config;
use function HireInSocial\symfony;
use HireInSocial\Tests\Application\Context\DatabaseContext;
use function HireInSocial\bootstrap;
use function HireInSocial\dbal;
use function HireInSocial\system;
use HireInSocial\UserInterface\Symfony\SymfonyKernel;
use phpDocumentor\Reflection\Types\Static_;

class WebTestCase extends \Symfony\Bundle\FrameworkBundle\Test\WebTestCase
{
    protected static $config;
    protected static $system;

    /**
     * @var \HireInSocial\Tests\Application\Context\SystemContext
     */
    protected $systemContext;

    /**
     * @var DatabaseContext
     */
    protected $databaseContext;

    protected static function getKernelClass()
    {
        return SymfonyKernel::class; // TODO: Change the autogenerated stub
    }

    protected static function createKernel(array $options = array())
    {
        return symfony(static::config(), static::system());
    }

    protected static function config() : Config
    {
        if (!static::$config) {
            static::$config = bootstrap(ROOT_DIR);
        }

        if (static::$config->getString(Config::ENV) !== 'test') {
            throw new \RuntimeException(sprintf('Expected environment "test" but got "%s"', static::$config->getString(Config::ENV) ));
        }

        return static::$config;
    }

    protected static function system() : System
    {
        if (!static::$system) {
            static::$system = system(static::config());
        }

        return static::$system;
    }

    public function setUp()
    {
        $config = static::config();

        $this->systemContext = new \HireInSocial\Tests\Application\Context\SystemContext(static::system());
        $this->databaseContext = new DatabaseContext(dbal($config));

        $this->databaseContext->purgeDatabase();
    }
}