name: Github CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run Full Testsuite
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.2
        env:
          POSTGRES_USER: hireinsocial
          POSTGRES_PASSWORD: hireinsocial
          POSTGRES_DB: hireinsocial_test
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379/tcp
    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
          coverage: none
          extension: mbstring, imap, intl, phpdbg

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependecies through composer
        working-directory: ./php/hireinsocial
        run: composer install

      - name: Run testsuite
        working-directory: ./php/hireinsocial
        run: composer test
        env:
          HIS_REDIS_DSN: redis://localhost:${{ job.services.redis.ports[6379] }}
          HIS_DB_PORT: ${{ job.services.postgres.ports[5432] }}

      - name: Run mutation tests
        run: phpdbg -qrr ./vendor/bin/infection -vvv --test-framework-options='--testsuite=unit' --only-covered
        working-directory: ./php/hireinsocial

