name: CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Change working directory
      run: cd php/hireinsocial
    - name: Install dependecies through composer
      run: composer install 
    - name: Run testsuite
      run: composer test
      
